### PR TITLE
Oauth

### PR DESCRIPTION
**Pull request by omarshokry193**

### CODE REVIEW

**Review by Emad-Eldin-G — APPROVED** [review]
Great work omar

**Comment by Emad-Eldin-G** [comment]
Please delete the pycache files before merging to resolve conflicts.

**Comment by omarshokry193** [comment]
Do I merge or wait for @mryoyo133 to review the pull request @Emad-Eldin-G ?

**Comment by Emad-Eldin-G** [comment]
> Do I merge or wait for @mryoyo133 to review the pull request @Emad-Eldin-G ?

Wait for his review, so we can all be on the same page

**Review by mryoyo133 — APPROVED** [review]

**Pull request merged**
